export const SET_ISLOADING = 'SET_ISLOADING';
export const SET_ISSUBMITTING = 'SET_ISSUBMITTING';

export const PRODUCTS_RECEIVED = 'PRODUCTS_RECEIVED';
export const PRODUCT_RECEIVED = 'PRODUCT_RECEIVED';
export const PRODUCT_REMOVED = 'PRODUCT_REMOVED';

export const REVIEW_ADDED = 'REVIEW_ADDED';

export const SET_PAGE_NUMBER = 'SET_PAGE_NUMBER';
